"""collecthive."""

import json
from pathlib import Path
from typing import Any, Dict

from flask import Flask, current_app
from flask_inertia import Inertia, render_inertia
from flask_pymongo import PyMongo

ROOT_DIR = Path(__file__).parents[1]
MANIFEST_FILE = ROOT_DIR / "static" / "dist" / "manifest.json"

mongo = PyMongo()


def load_manifest() -> Dict[str, Dict[str, Any]]:
    """Load JSON manifest if generated by the front."""
    try:
        with open(MANIFEST_FILE) as fi:
            manifest = json.load(fi)
    except Exception:
        current_app.logger.debug("Manifest file not found")
        manifest = {}

    return {"manifest": manifest}


def index():
    """Render main view."""
    return render_inertia("Index")


def create_app(config_filename: str) -> Flask:
    """Create app instance from Python config file."""
    app = Flask(
        __name__,
        template_folder=ROOT_DIR / "templates",
        static_folder=ROOT_DIR / "static" / "dist",
    )
    app.config.from_pyfile(f"{config_filename}.py")

    Inertia(app)
    mongo.init_app(app)

    app.context_processor(load_manifest)

    app.add_url_rule("/", "index", index)

    return app
