"""collecthive."""

import json
from pathlib import Path
from typing import Any, Dict

from flask import Flask, current_app, get_flashed_messages, send_from_directory
from flask_inertia import Inertia, render_inertia
from flask_pymongo import PyMongo
from werkzeug.utils import safe_join

ROOT_DIR = Path(__file__).parents[1]
MANIFEST_FILE = ROOT_DIR / "static" / "dist" / "manifest.json"

mongo = PyMongo()
inertia = Inertia()


def load_manifest() -> Dict[str, Dict[str, Any]]:
    """Load JSON manifest if generated by the front."""
    try:
        with open(MANIFEST_FILE) as fi:
            manifest = json.load(fi)
    except Exception:
        current_app.logger.debug("Manifest file not found")
        manifest = {}

    return {"manifest": manifest}


def index():
    """Render main view."""
    return render_inertia("Index")


def uploads(folder: str, filename: str):
    """Serve uploads file."""
    filedir = safe_join(current_app.config["UPLOAD_DIR"], folder)
    return send_from_directory(filedir, filename)


def create_app(config_filename: str) -> Flask:
    """Create app instance from Python config file."""
    app = Flask(
        __name__,
        template_folder=ROOT_DIR / "templates",
        static_folder=ROOT_DIR / "static" / "dist",
    )
    app.config.from_pyfile(f"{config_filename}.py")

    inertia.init_app(app)
    mongo.init_app(app)

    from collecthive.books.views import books_bp

    app.add_url_rule("/", "index", index)
    app.add_url_rule("/uploads/<string:folder>/<string:filename>", "uploads", uploads)
    app.register_blueprint(books_bp, url_prefix="/books")

    app.context_processor(load_manifest)

    inertia.share("messages", get_flashed_messages)

    return app
